server:
  port: 9000
spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:h2:mem:account-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /ms-account-docs
    enabled: true
  api-docs:
    path: /v3/ms-account-docs
